server:
  port: 8040
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    status-page-url: http://127.0.0.1:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
spring:
  application:
    name: cloud-service-book
  datasource:
      type: com.mchange.v2.c3p0.ComboPooledDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 60
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/book_borrow?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=true
  user: root
  password: root
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 200
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "